### ISSUE TITLE
Source code in Debian package does not reflect the correct source code

### ISSUE THREAD

**Issue by quovide** [Azure/AZNFS-mount#132]
Somehow the built packages are not correct at:
https://github.com/Azure/AZNFS-mount/releases/tag/2.0.7

The source code "Source code (zip)" file has to correct latest changes that match the tag,
but all the built packages do not!

I didn't investigate which version it uses but there must be something wrong with the Github action or the package script

**Comment by quovide** [comment]
OK, suddenly I see the reason. The official release has been built off another branch. Why??
![image](https://github.com/Azure/AZNFS-mount/assets/5293839/474b6e89-b453-4f2f-bd57-33c202ff6224)

**Comment by cagrawal-msft** [comment]
Thanks for raising the issue. We are working to fix this.

**Comment by palashvij-msft** [comment]
Hi, this is fixed as part of release 2.0.10 (https://github.com/Azure/AZNFS-mount/releases/tag/2.0.10)

Thanks!
