### ISSUE TITLE
/etc/fstab entry won't load on reboot

### ISSUE THREAD

**Issue by abhai2k** [Azure/AZNFS-mount#62]
I have added entry as specified in https://learn.microsoft.com/en-us/azure/storage/blobs/network-file-system-protocol-support-how-to guide. However on reboot, the path does not mount as the aznfswatchdog is still loaded.

Error in /opt/microsoft/aznfs/aznfs.log
`Sun Jun 04 2023 18:27:57.660 anq-ci-internal-gitlab 431: aznfswatchdog service not running!`

entry in /etc/fstab
`XXXXXXXXXX.blob.core.windows.net:/XXXXXXXXX/YYYY  /ZZZZ    aznfs defaults,sec=sys,vers=3,nolock,proto=tcp,nofail    0 0`

It works fine if I remove aznfs and set it to just nfs.

Possible fix:
in /opt/microsoft/aznfs/mountscript.sh, modifying ensure_aznfswatchdog function to start the service. Not the best idea but it works.

**Comment by dalekreitler-bnl** [comment]
I have also run into this issue and would be interested to hear a solution besides modifying the mount script.

**Comment by cagrawal-msft** [comment]
In the fstab entry, user has to give '_netdev' option as well so that systemd can understand that 'aznfs' is a remote FS and aznfswactchdog has started before remote-fs.target. To ensure latter, aznfswatchdog.service has been updated. 

Now '/etc/fstab' entry will be: 
'<storage-account-name>.blob.core.windows.net:/<storage-account-name>/<container-name>  /nfsdata    aznfs defaults,sec=sys,vers=3,nolock,proto=tcp,nofail,_netdev    0 0'

Documentation will be updated soon.

**Comment by cagrawal-msft** [comment]
Official doc has also been updated for /etc/fstab entry. Can check it out. 
https://learn.microsoft.com/en-us/azure/storage/blobs/network-file-system-protocol-support-how-to

**Comment by darylnz** [comment]
Thank you, I ran into this issue while testing on RHEL 8.x server. 
The entry and the 1.02 update appears to have solved the issue now for my test environment.

**Comment by anthonysomerset** [comment]
I appear to be bumping into this issue on SLES 15 hosts even with the _netdev option in fstab

**Comment by umeshmane** [comment]
> Official doc has also been updated for /etc/fstab entry. Can check it out. https://learn.microsoft.com/en-us/azure/storage/blobs/network-file-system-protocol-support-how-to

for RHEL 9, even after adding _netdev , getting mount.nfs: mount point /mnt/ngsworkspaces does not exist in aznfs.log, in /opt/microsoft/aznfs/data
