### ISSUE TITLE
does aznfs already support china everment?and if we use aks and pod mount azure blob via nfs, how we fix or install aznfs in pod?

### ISSUE THREAD

**Issue by wbypai** [Azure/AZNFS-mount#65]
on china vm

[root@work-c7-east2-t nfs]# mount -t aznfs -o sec=sys,vers=3,nolock,proto=tcp case8822.blob.core.chinacloudapi.cn:/case8822/nfs  /mnt/nfs
Not a valid Azure Blob NFS endpoint: case8822.blob.core.chinacloudapi.cn!
Must be of the form 'account.blob.core.windows.net'!
[root@work-c7-east2-t nfs]# 

and if we use aks and pod mount azure blob via nfs, how we fix it or install aznfs in pod?

**Comment by wbypai** [comment]
I found "is_valid_blob_fqdn()" method only valid global blob fqdn, not include china blob, so after I comment line 621-625, it works for china blob.
so please help to fix the code.

and if we use aks and pod mount azure blob via nfs, how we fix it or install aznfs in pod?


rpm -ql aznfs-1.0.0-1.x86_64
/lib/systemd/system/aznfswatchdog.service
/opt/microsoft/aznfs/common.sh
/opt/microsoft/aznfs/mountscript.sh
/sbin/mount.aznfs
/usr/lib/.build-id
/usr/lib/.build-id/b1
/usr/lib/.build-id/b1/c5428fb381d2e7a13328e3dd062128747aeda9
/usr/sbin/aznfswatchdog

grep 'windows.net' /opt/microsoft/aznfs/mountscript.sh
# Check if the given string is a valid blob FQDN (<accountname>.blob.core.windows.net).
    [[ $1 =~ ^([a-z0-9]{3,24})(.z[0-9]+)?.blob(.preprod)?.core.windows.net$ ]]
# Get blob endpoint from account.blob.core.windows.net:/account/container.
        eecho "Share to be mounted must be of the form 'account.blob.core.windows.net:/account/container'."
# Get /account/container from account.blob.core.windows.net:/account/container.
        eecho "Share to be mounted must be of the form 'account.blob.core.windows.net:/account/container'."
# [account.blob.core.windows.net:/account/container /mnt/aznfs -o rw,tcp,nolock,nconnect=16]
#    eecho "Must be of the form 'account.blob.core.windows.net'!"
    eecho "Share to be mounted must be of the form 'account.blob.core.windows.net:/account/container'!"


65 is_valid_blob_fqdn()
66 {
67     [[ $1 =~ ^([a-z0-9]{3,24})(.z[0-9]+)?.blob(.preprod)?.core.windows.net$ ]]
68 }

    621 #if ! is_valid_blob_fqdn "$nfs_host"; then
    622 #    eecho "Not a valid Azure Blob NFS endpoint: ${nfs_host}!"
    623 #    eecho "Must be of the form 'account.blob.core.windows.net'!"
    624 #    exit 1
    625 #fi

**Comment by sherryhao** [comment]
Yes, I'm facing the same issue. And after commented out the lines from 621 to 625, it works.
As lots of customer are going to migrate to aznfs as notification are broadcasted to all Azure China users, would you please help to fix it in the new release?

**Comment by linuxsmiths** [comment]
Thanks for reporting this!
Will fix this in the next release.

**Comment by cagrawal-msft** [comment]
We have fixed this issue. Please try out release 1.0.2
Thanks
