### ISSUE TITLE
Troubleshooting Access to Mounted Storage

### ISSUE THREAD

**Issue by alekseyen** [Azure/AZNFS-mount#74]
Hello! I'm facing an issue with accessing my storage after successfully mounting it. 
Despite following a tutorial: https://learn.microsoft.com/en-us/azure/storage/blobs/network-file-system-protocol-support-how-to, I  successfully mount the storage, but I find that both 'cd' and 'sudo ls' commands are not working as expected with my storage. 

Could anyone kindly offer some guidance on how to successfully access my files in the operating system? Your help would be greatly appreciated!

**Comment by cagrawal-msft** [comment]
Can you once verify if the mount is done successfully using "nfsstat -m" command. Also check "/opt/microsoft/aznfs/aznfs.log" file for any error. If there are any, can you share it here? Don't share any personal information.
