### ISSUE TITLE
there needs "then"

### ISSUE THREAD

**Issue by jkl2554** [Azure/AZNFS-mount#81]
https://github.com/Azure/AZNFS-mount/blob/73829dec6e9ac80695fc494a3b81addd9e175ac6/src/aznfswatchdog#L153

to 
` if [ $? -eq 0 ] && [ -n "$conntrack_timeo_timew" -a $conntrack_timeo_timew -gt $AZNFS_TIMEWAIT_TIMEOUT ]; then`

**Comment by cagrawal-msft** [comment]
@jkl2554 Thanks for pointing out the issue which got pushed in latest release. This will be fixed soon.
