### ISSUE TITLE
Release 2.0.0 breaks installs from script runner

### ISSUE THREAD

**Issue by nat-muon** [Azure/AZNFS-mount#96]
# Summary

I am having an issue installing AZNFS-mount with the latest release using the install instructions provided. 
`wget -O - -q https://github.com/Azure/AZNFS-mount/releases/latest/download/aznfs_install.sh | bash`

I am currently running this install command as part of a build script for a Virtual Machine image, using a tool called [packer](https://www.packer.io/). 

The failure we are seeing is: 
`/dev/tty: No such device or address`

This failure is currently breaking all builds.

The only workaround at this time is to pin the release before 2.0.0 like so:
`wget -O - -q https://github.com/Azure/AZNFS-mount/releases/1.0.10/download/aznfs_install.sh | bash`
but I would prefer to install the latest version.

When I run the command on it's own from a command line, I see that there's a whiptail prompt about auto-update that pops up, which I suspect is the root cause of the issue. 

I believe it should be possible to run this install as part of a build script, rather than manually from a command line. Is there any way we can bypass the prompt without enabling auto-update?

Would appreciate any help you can provide, thanks!

**Comment by palashvij-msft** [comment]
Hello @nat-muon, Thanks for reporting the issue. We're looking into this specific issue, surely will get back to you soon after the fix.
Thanks

**Comment by palashvij-msft** [comment]
Update @nat-muon, We've addressed your issue in the our latest release (https://github.com/Azure/AZNFS-mount/releases/tag/2.0.2). Pls go through readme for steps of non-interactive installation. Pls try with that and let us know in case of any issues. 

Thanks
Palash

**Comment by nat-muon** [comment]
@palashvij-msft Just tested it out and it worked! Greatly appreciate the quick turnaround on this.
